config/routes.rb
Rails.application.routes.draw do
  
  resources :notifications do
    collection do
    get 'remove_all'
  end
end
  
  
  devise_scope :user do
  get 'signup', to: 'devise/registrations#new'
end
  
  devise_scope :user do
  get 'login', to: 'devise/sessions#new'
end

  resources :patients do
    resources :patientnotes
  end
  
  devise_for :users, :controllers => {:registrations => "registrations"}
  root to: 'pages#index'
  
get '/news' => 'news#index'  
  
end

app/models/patientnote.rb
class Patientnote < ActiveRecord::Base
    belongs_to :patient
end

app/controllers/patientnotes_controller.rb
class PatientnotesController < ApplicationController
    

  def index
  @patient = Patient.find(params[:patient_id])
  @patientnotes = @patient.patientnotes
  end
  
  def show
      @patient = Patient.find(params[:patient_id])
      @patientnote = @patient.patientnotes.find(params[:id])
  end
  
  def new
      @patient = Patient.find(params[:patient_id])
      @patientnote = @patient.patientnotes.new
  end

  def create
    unless current_user.doctor?
        redirect_to root_path, :alert => "Only Doctor Staff can add patients patient notes!"
    end
    @patient = Patient.find(params[:patient_id])
    @patientnote = @patient.patientnotes.new(patientnote_params)
    if @patientnote.save 
      redirect_to patient_path(@patient)
    else
      redirect_to patient_path
    end
  end
  

  def edit
  @patient = Patient.find(params[:patient_id])
  @patientnote = @patient.patientnotes.find(params[:id])
  end


  def update
  @patient = Patient.find(params[:patient_id])
  @patientnote = @patient.patientnotes.find(params[:id])
  if @patientnote.update_attributes(params.require(:patientnote).permit(:title, :content))
  redirect_to patient_path(@patient)
  else
  render :action => "edit"
  end
  end

  def destroy
  @patient = Patient.find(params[:patient_id])
  @patientnote = @patient.patientnotes.find(params[:id])
  @patientnote.destroy
  respond_to do |format|
  format.html { redirect_to patient_path(@patient)}
  format.xml { head :ok }
  end
  end

  
  private
  
  def patientnote_params
      params.require(:patientnote).permit(:date, :title, :content)
  end

end

app/helpers/patientnotes_helper.rb
module PatientnotesHelper
    
    def modal_content_partial_path
        if current_user.doctor?
            'patientnotes/show/doctor_modal_content'
        else
            'patientnotes/show/admin_modal_content'
        end
    end
    
end

app/views/patientnotes/_modal.html.erb
<!-- Modal -->
<div  class="modal myModal" 
      tabindex="-1" 
      role="dialog" 
      aria-labelledby="myModalLabel">
  <div class="modal-dialog modal-lg" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <span class="posted-by"></span>
        <button type="button" 
                class="close" 
                data-dismiss="modal" 
                aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
        <div class="modal-body">
          <%= render modal_content_partial_path %>
        </div><!-- modal-body -->
    </div>
  </div>
</div>

app/views/patientnotes/_patientnote.html.erb
<div class="col-sm-3 single-post-card" id=<%= patient_patientnotes_path(@patient, patientnote)%>>
  <div class="card">
    <div class="card-block">
      <h4 class="post-text">
        <%= patientnote.date %>
      </h4>
      <div class="post-content">
        <div class="title">
         <%= patientnote.title%>
        </div>
        <div class="content">
         <%= patientnote.content%>
        </div>
         <%= link_to 'Destroy', patient_patientnote_path(@patient, patientnote.id), :confirm => 'Are you sure?', :method => :delete , class: 'delete_button' %>
         <%= link_to 'Edit', edit_patient_patientnote_path(@patient, patientnote.id), class: 'edit_button' %>
        </div>
      </div>
  </div><!-- card -->
</div><!-- col-sm-3 -->

app/views/patientnotes/edit.html.erb
<div class="container new-patientnote">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1>Add a new Patient Note:</h1>
        <%= render 'patientnotes/new/patientnote_form' %>
    </div>
  </div>
</div>

app/views/patientnotes/new.html.erb
<div class="container new-patientnote">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <h1>Add a new Patient Note:</h1>
        <%= render 'patientnotes/new/patientnote_form' %>
    </div>
  </div>
</div>

app/views/patientnotes/show.html.erb
<%= render 'patientnotes/modal' %>
<div id="single-post-content" class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <div class="posted-by">Patient: <%= @patientnote.patient.name %></div>
      <h3>Date: <%= @patientnote.date %></h3>
      <h3>Title: <%= @patientnote.title %></h3>
      <p>Content: <%= @patientnote.content %></p>
    </div>
  </div><!-- row -->
</div>